core/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static


def redirect_login(request):
    return redirect(reverse('users:login'))

urlpatterns = [
    
    path("admin/", admin.site.urls),
    path("auth/", include("user.urls", namespace="users")),
    path("superuser/", include("superuser.urls", namespace="superuser")),
    path("material/", include("materials.urls", namespace="materials")),
    path("sales/", include("sales.urls", namespace="sales")),
    path("spare/", include("spare.urls", namespace="spare")),
    path("director/", include("director.urls", namespace="director")),
    path("", redirect_login)
]


urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superuser/urls.py
from django.urls import path
from superuser.forms import SellBrak
from superuser.views import (
    BrakListView,
    DesignPriceHistoryView,
    DesignView,
    ExpenditureView,
    FinanceView,
    HomePageView,
    LabelExportView,
    LabelHistoryListView,
    LabelListView,
    LabelTypeDeleteView,
    LabelTypeListView,
    LabelTypeUpdateView,
    MaterialInActiveCancelView,
    MaterialInActiveUpdateView,
    MaterialTypeListView,
    MaterialTypeUpdateView,
    MaterialTypeDeleteView,
    MaterialHistoryListView,
    MaterialInActivesListView,
    ProductionMaterialHistory,
    SellBrakView,
    SpareListView,
    SpareTypeDeleteView,
    SpareTypeListView,
    SpareTypeUpdateView,
    SpareHistoryListView,
    SpareExportView,
    DesignDeleteView,
    StockBarcodeView,
    StockView,
    UserView,
    WorkerListCreateView,
    admin_account_details,
    admin_accounts_history,
    admin_design_details,
    admin_edit_design_materials,
    admin_insert_design_materials,
    admin_pre_production_send,
    admin_pre_production_send_list,
    admin_sales,
    admin_unclosed_salaries,
    admin_worker_account,
    admin_worker_credits,
    admin_worker_details,
    admin_worker_stats,
    admin_workers,
    production_send_yaim,
    remove_local_storage,
    sales_history,
    stock_sell,
)

from superuser.utils.generate_xls import *

app_name = "superuser"

urlpatterns = [
    path("dashboard/", HomePageView.as_view(), name="dashboard"),
    path(
        "dashboard/material-types/",
        MaterialTypeListView.as_view(),
        name="material_types",
    ),
    path(
        "dashboard/material-types/edit/<int:pk>/",
        MaterialTypeUpdateView.as_view(),
        name="material_types_update",
    ),
    path(
        "dashboard/material-types/delete/<int:pk>/",
        MaterialTypeDeleteView.as_view(),
        name="material_types_delete",
    ),
    path(
        "dashboard/history/",
        MaterialHistoryListView.as_view(),
        name="material_history",
    ),
    path(
        "dashboard/material/inactives/",
        MaterialInActivesListView.as_view(),
        name="material_inactives",
    ),
    path(
        "dashboard/material/inactives/confirm/<int:pk>/",
        MaterialInActiveUpdateView.as_view(),
        name="material_inactives_confirm",
    ),
    path(
        "dashboard/material/inactives/cancel/<int:pk>/",
        MaterialInActiveCancelView.as_view(),
        name="material_inactives_cancel",
    ),
]

# SPARE VIEWS
urlpatterns += [
    path("dashboard/spare/", SpareListView.as_view(), name="spare_list"),
    path("dashboard/spare/types/", SpareTypeListView.as_view(), name="spare_types"),
    path(
        "dashboard/spare/types/edit/<int:pk>/",
        SpareTypeUpdateView.as_view(),
        name="spare_types_update",
    ),
    path(
        "dashboard/spare/types/delete/<int:pk>/",
        SpareTypeDeleteView.as_view(),
        name="spare_types_delete",
    ),
    path(
        "dashboard/spare/history/",
        SpareHistoryListView.as_view(),
        name="spare_history",
    ),
    path(
        "dashboard/spare/export/",
        SpareExportView.as_view(),
        name="spare_export",
    ),
]

# LABEL VIEWS
urlpatterns += [
    path("dashboard/label/", LabelListView.as_view(), name="label_list"),
    path("dashboard/label/types/", LabelTypeListView.as_view(), name="label_types"),
    path(
        "dashboard/label/types/edit/<int:pk>/",
        LabelTypeUpdateView.as_view(),
        name="label_types_update",
    ),
    path(
        "dashboard/label/types/delete/<int:pk>/",
        LabelTypeDeleteView.as_view(),
        name="label_types_delete",
    ),
    path(
        "dashboard/label/history/",
        LabelHistoryListView.as_view(),
        name="label_history",
    ),
    path(
        "dashboard/label/export/",
        LabelExportView.as_view(),
        name="label_export",
    ),
]

# DESIGN VIEWS
urlpatterns += [
    path("dashboard/design/home/", DesignView.as_view(), name="design_home"),
    path(
        "dashboard/design/insert-materials/<int:pk>/",
        admin_insert_design_materials,
        name="design-insert-materials",
    ),
    path(
        "dashboard/design/edit-materials/<int:pk>/",
        admin_edit_design_materials,
        name="design-edit-materials",
    ),

    path(
        "dashboard/design/details/<int:pk>/",
        admin_design_details,
        name="design-details",
    ),
    path("dashboard/design/delete/<int:pk>/", DesignDeleteView.as_view(), name="design_delete"),
    path("dashboard/design/price/history/", DesignPriceHistoryView.as_view(), name="design_price_history"),

]

urlpatterns += [
    path("dashboard/production/material/history/", ProductionMaterialHistory.as_view(),
         name="production_material_history"),
    path("dashboard/production/brak/", BrakListView.as_view(), name="brak_list"),
    path("dashboard/production/brak/sell/<int:pk>/", SellBrakView.as_view(), name="sell_brak"),
    path("dashboard/production/send-yaim/", production_send_yaim, name="send_yaim"),
]

urlpatterns += [
    path("dashboard/expenditure/", ExpenditureView.as_view(), name="expenditure"),
]

urlpatterns += [
    path("dashboard/profiles/", UserView.as_view(), name="profiles"),
]

# FINANCE
urlpatterns += [
    path("dashboard/finance/", FinanceView.as_view(), name="finance"),
]

# PRE PRODUCTION
urlpatterns += [
    path("dashboard/pre-production/", admin_pre_production_send_list, name="pre-production"),
    path('dashboard/pre-production/send-list/<int:pk>', admin_pre_production_send,
         name='pre-production-send'),
]

# WORKERS

urlpatterns += [
    path("dashboard/workers/", admin_workers, name="workers"),
    path('dashboard/workers/<int:pk>/', admin_worker_details, name='worker-details'),
    path('dashboard/workers/account/<int:pk>/', admin_worker_account, name='worker-accounts'),
    path('dashboard/workers/account-details/<int:pk>/', admin_account_details, name='worker-account'),
    path('dashboard/workers/account/<int:wid>/stats/<int:aid>/', admin_worker_credits, name='worker-stats'),
    path('dashboard/workers/unclosed-accounts/', admin_unclosed_salaries, name='unclosed-accounts'),
    path('dashboard/workers/history/', admin_accounts_history, name='accounts-history'),
    path('dashboard/workers/stats/', admin_worker_stats, name='register-workers-stats'),
]

# STOCK

urlpatterns += [
    path("dashboard/stock/", StockView.as_view(), name="stock"),
    path("dashboard/stock/sell/", stock_sell, name="stock-sell"),
    path('dashboard/stock/remove/', remove_local_storage, name='stock-remove'),
    path('dashboard/sales/', admin_sales, name='sales'),
    path('dashboard/sales/history', sales_history, name='sales-history'),

    path("dashboard/stock/barcodes/", StockBarcodeView.as_view(), name="stock-barcodes"),
]

# EXCEL GENERATORS
urlpatterns += [
    path(
        "dashboard/material/history/generate-xls/",
        GenerateMaterialHistoryExcel.as_view(),
        name="material_history_xls",
    ),
    path(
        "dashboard/material/generate-xls/",
        GenerateMaterialExcel.as_view(),
        name="material_xls",
    ),
    path(
        "dashboard/spare/history/generate-xls/",
        GenerateSpareHistoryExcel.as_view(),
        name="spare_history_xls",
    ),
    path(
        "dashboard/spare/generate-xls/",
        GenerateSpareExcel.as_view(),
        name="spare_xls",
    ),
    path(
        "dashboard/label/history/generate-xls/",
        GenerateLabelHistoryExcel.as_view(),
        name="label_history_xls",
    ),
    path(
        "dashboard/label/generate-xls/",
        GenerateLabelExcel.as_view(),
        name="label_xls",
    ),

    path(
        "dashboard/design/generate-xls/",
        GenerateDesignExcel.as_view(),
        name="design_xls",
    ),

    path(
        "dashboard/expenditure/generate-xls/",
        GenerateExpenditureExcel.as_view(),
        name="expenditure_xls",
    ),

    path(
        "dashboard/finance/generate-xls/",
        GenerateFinanceExcel.as_view(),
        name="finance_xls",
    ),
    path(
        "dashboard/design/history/generate-xls/",
        GenerateDesignPriceHistoryExcel.as_view(),
        name="design_price_history_xls",
    ),
]

# TODO
# * Nazoratchi / Sotuvchi / Zapchast / Seryo ----> Profillar


# Pul kirimlari
# Brak mahsulot
# Savdo

templates/superadmin/label/export.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block sidebar_items %}
{% include '../sidebar.html' %}
{% endblock sidebar_items %}


{% block content %}

<h3 class="mt-2">Etiketika eksport</h3>
<hr>
<br>


{% if query and found %}
<form method="post">
    {% csrf_token %}
    <div class="column-2">
        <div class="form-group mb-3">
            <label for="">Etiketika turi*</label>
            <select name="object" id="" class="form-control" required>
                {% for obj in object_list %}
                <option value="{{obj.id}}">{{obj.label.name}} - {{obj.amount}}
                    {{obj.get_amount_type_display}} | {{obj.confirmed_price}} {{obj.get_price_type_display}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group mb-3">
            <label for="">Miqdori*</label>
            <input type="text" name="amount" class="form-control" required>
        </div>

        <div class="form-group mb-3">
            <label for="">Qayerga*</label>
            <select name="where" id="" class="form-control" required>
                {% for key, val in where %}

                {% if key == 'yaim' %}
                <option value="{{key}}">{{val}}</option>

                {% endif %}

                {% endfor %}
            </select>
        </div>


    </div>
    <a href="{% url 'superuser:label_export' %}" class="btn btn-secondary">Ortga</a>

    <button type="submit" id="submit-btn" class="btn btn-primary">Kiritish</button>
</form>
{% else %}
<form method="get">
    <div class="column-2">
        <div class="form-group mb-3">
            <label for="">Etiketika nomi</label>
            <input type="text" name="title" class="form-control" autofocus>
        </div>
    </div>
    <button type="submit" id="submit-btn" class="btn btn-primary">Qidirish</button>
</form>
{% endif %}

<br>

<hr>

<br>

<a href="{% url 'superuser:label_xls' %}" class="btn btn-success mb-3">Excelda olish </a>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Etiketika</th>
                <th>Miqdori</th>
                <th>Narxi</th>
                <th>Tasdiqlangan narxi</th>
                <th>Holati</th>
                <th>Izoh</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
            <tr>
                <td>{{forloop.counter0|add:page_obj.start_index}}</td>
                <td>{{obj.label.name}}</td>
                <td>{{obj.amount|intcomma}} {{obj.get_amount_type_display}} </td>
                <td>{{obj.price|intcomma}} {{obj.get_price_type_display}}</td>
                <td>{{obj.confirmed_price|intcomma}} {{obj.get_price_type_display}}</td>
                <td>{{obj.get_is_active_display}}</td>
                <td>{{obj.import_comment}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



{% if page_obj.has_next or page_obj.has_previous %}

<div class="pagination">
    <span class="step-links">

        <br>
        <h6 class="current">
            {{ page_obj.paginator.num_pages }} - {{ page_obj.number }} sahifa.
            </h4>
            <br>


            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page=1" {% endif %}>&laquo;Birinchi</a>
            |
            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }}"
                {%endif %}>‹ Oldingi</a> |




            <a class="pagination-btn" {% if page_obj.has_next %}
                href="?page={{ page_obj.next_page_number }} {% endif %}">Keyingi ›</a> |
            <a class="pagination-btn" {% if page_obj.has_next %} href="?page={{ page_obj.paginator.num_pages }}"
                {%endif%}>Oxirgi &raquo;</a>

    </span>
</div>

{% endif %}



{% endblock content %}

templates/superadmin/label/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block sidebar_items %}
{% include '../sidebar.html' %}
{% endblock sidebar_items %}


{% block content %}

<h3 class="mt-2">Etiketika ombori</h3>
<hr>
<br>


{% if request.user.role != "DIRECTOR" %}
<form method="post">
    <div class="column-2">
        {% csrf_token %}
        {{form|crispy}}
    </div>
    <button type="submit" id="submit-btn" class="btn btn-primary">Kiritish</button>
</form>
<br>

<hr>

<br>
{% endif %}
    

<a href="{% url 'superuser:label_xls' %}" class="btn btn-success mb-3">Excelda olish </a>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Etiketika nomi</th>
                <th>Miqdori</th>
                <th>Narxi</th>
                <th>Tasdiqlangan narxi</th>
                <th>Holati</th>
                <th>Izoh</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
            <tr>
                <td>{{forloop.counter0|add:page_obj.start_index}}</td>
                <td>{{obj.label.name}}</td>
                <td>{{obj.amount|intcomma}} {{obj.get_amount_type_display}} </td>
                <td>{{obj.price|intcomma}} {{obj.get_price_type_display}}</td>
                <td>{{obj.confirmed_price|intcomma}} {{obj.get_price_type_display}}</td>
                <td>{{obj.get_is_active_display}}</td>
                <td>{{obj.import_comment}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



{% if page_obj.has_next or page_obj.has_previous %}

<div class="pagination">
    <span class="step-links">

        <br>
        <h6 class="current">
            {{ page_obj.paginator.num_pages }} - {{ page_obj.number }} sahifa.
            </h4>
            <br>


            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page=1" {% endif %}>&laquo;Birinchi</a>
            |
            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }}"
                {%endif %}>‹ Oldingi</a> |




            <a class="pagination-btn" {% if page_obj.has_next %}
                href="?page={{ page_obj.next_page_number }} {% endif %}">Keyingi ›</a> |
            <a class="pagination-btn" {% if page_obj.has_next %} href="?page={{ page_obj.paginator.num_pages }}"
                {%endif%}>Oxirgi &raquo;</a>

    </span>
</div>

{% endif %}



{% endblock content %}

templates/superadmin/label/label_history.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block sidebar_items %}
{% include '../sidebar.html' %}
{% endblock sidebar_items %}


{% block content %}

<h3 class="mt-2">Operatsiyalar tarixi | Etiketika</h3>
<hr>

<br>

<a href="{% url 'superuser:label_history_xls' %}" class="btn btn-success mb-3">Excelda olish </a>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th style="width: 30px;">#</th>
                <th>Etiketika nomi</th>
                <th>Bajaruvchi</th>
                <th>Operatsiya turi</th>
                <th>Miqdor</th>
                <th>Narx</th>
                <th>Qayerga</th>
                <th>Sana</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
            <tr>
                <td>{{forloop.counter0|add:page_obj.start_index}}</td>
                <td>{{obj.label}}</td>
                <td>{{obj.executor.role}}</td>
                <td>{{obj.get_action_display}}</td>
                <td>{{obj.amount|intcomma}} {{obj.get_amount_type_display}}</td>
                <td>{{obj.price|intcomma}} {{obj.get_price_type_display}}</td>
                <td>{{obj.get_where_display}}</td>
                <td>{{obj.created_at}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



{% if page_obj.has_next or page_obj.has_previous %}

<div class="pagination">
    <span class="step-links">

        <br>
        <h6 class="current">
            {{ page_obj.paginator.num_pages }} - {{ page_obj.number }} sahifa.
            </h4>
            <br>


            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page=1" {% endif %}>&laquo;Birinchi</a>
            |
            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }}"
                {%endif %}>‹ Oldingi</a> |




            <a class="pagination-btn" {% if page_obj.has_next %}
                href="?page={{ page_obj.next_page_number }} {% endif %}">Keyingi ›</a> |
            <a class="pagination-btn" {% if page_obj.has_next %} href="?page={{ page_obj.paginator.num_pages }}"
                {%endif%}>Oxirgi &raquo;</a>

    </span>
</div>

{% endif %}



{% endblock content %}

templates/superadmin/label/label_type_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block sidebar_items %}
{% include '../sidebar.html' %}
{% endblock sidebar_items %}


{% block content %}

<h3 class="mt-2">Etiketika turlari</h3>
<hr>
<br>

<form method="post">
    {% csrf_token %}


    <div class="mb-2">
        <b>{{object}}</b>
    </div>

    <a href="{% url 'superuser:label_types' %}" class="btn btn-secondary">Ortga</a>

    <button {% if restricted %} disabled {% endif %} type="submit" id="submit-btn"
        class="btn btn-danger">O'chirish</button>


    <div class="mt-2">
        {% if restricted %}
        <span class="badge bg-danger">
            Ushbu etiketika turini o'chirish mumkin emas. Omborda ushbu mahsulot mavjud.
        </span>
        {% endif %}
    </div>


</form>
<br>

<hr>





{% endblock content %}

templates/superadmin/label/label_type_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block sidebar_items %}
{% include '../sidebar.html' %}
{% endblock sidebar_items %}


{% block content %}

<h3 class="mt-2">Etiketika turlari</h3>
<hr>
<br>

<form method="post">
    <div class="column-2">
        {% csrf_token %}
        {{form|crispy}}
    </div>
    <a href="{% url 'superuser:label_types' %}" class="btn btn-secondary">Ortga</a>

    <button type="submit" id="submit-btn" class="btn btn-primary">Yangilash</button>
</form>
<br>

<hr>





{% endblock content %}

templates/superadmin/label/label_types.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block sidebar_items %}
{% include '../sidebar.html' %}
{% endblock sidebar_items %}


{% block content %}

<h3 class="mt-2">Etiketika turlari</h3>
<hr>
<br>

<form method="post">
    <div class="column-2">
        {% csrf_token %}
        {{form|crispy}}
    </div>
    <button type="submit" id="submit-btn" class="btn btn-primary">Kiritish</button>
</form>
<br>

<hr>

<br>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th style="width: 30px;">#</th>
                <th>Etiketika nomi</th>
                <th style="width: 50px;">O'zgartirish</th>
                <th class="text-danger" style="width: 50px;">O'chirish</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
            <tr>
                <td>{{forloop.counter0|add:page_obj.start_index}}</td>
                <td>{{obj.name}}</td>
                <td><a href="{% url 'superuser:label_types_update' obj.pk %}"
                        class="btn btn-outline-dark">O'zgartirish</a>
                </td>
                <td><a href="{% url 'superuser:label_types_delete' obj.pk %}"
                        class="btn btn-outline-danger">O'chirish</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



{% if page_obj.has_next or page_obj.has_previous %}

<div class="pagination">
    <span class="step-links">

        <br>
        <h6 class="current">
            {{ page_obj.paginator.num_pages }} - {{ page_obj.number }} sahifa.
            </h4>
            <br>


            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page=1" {% endif %}>&laquo;Birinchi</a>
            |
            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }}"
                {%endif %}>‹ Oldingi</a> |




            <a class="pagination-btn" {% if page_obj.has_next %}
                href="?page={{ page_obj.next_page_number }} {% endif %}">Keyingi ›</a> |
            <a class="pagination-btn" {% if page_obj.has_next %} href="?page={{ page_obj.paginator.num_pages }}"
                {%endif%}>Oxirgi &raquo;</a>

    </span>
</div>

{% endif %}



{% endblock content %}