core/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static


def redirect_login(request):
    return redirect(reverse('users:login'))

urlpatterns = [
    
    path("admin/", admin.site.urls),
    path("auth/", include("user.urls", namespace="users")),
    path("superuser/", include("superuser.urls", namespace="superuser")),
    path("material/", include("materials.urls", namespace="materials")),
    path("sales/", include("sales.urls", namespace="sales")),
    path("spare/", include("spare.urls", namespace="spare")),
    path("director/", include("director.urls", namespace="director")),
    path("", redirect_login)
]


urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

director/urls.py
from django.urls import path

from director.views import ExpenditureView, FinanceView, HomePageView, LabelListView, SpareListView, StockView, \
    admin_pre_production_send_list, admin_sales, sales_history, MonitorPageView

app_name = 'director'

urlpatterns = [
    path('dashboard/', MonitorPageView.as_view(), name='dashboard'),
    path('dashboard/material/', HomePageView.as_view(), name='material'),
    path("dashboard/spare/", SpareListView.as_view(), name="spare"),
    path("dashboard/label/", LabelListView.as_view(), name="label"),
    path("dashboard/pre-production/", admin_pre_production_send_list, name="pre-production"),
    path("dashboard/stock/", StockView.as_view(), name="stock"),
    path('dashboard/sales/', admin_sales, name='sales'),
    path('dashboard/sales/history', sales_history, name='sales-history'),
    path("dashboard/expenditure/", ExpenditureView.as_view(), name="expenditure"),
    path("dashboard/finance/", FinanceView.as_view(), name="finance"),
    
    
]

materials/urls.py
from django.urls import path
from materials.views import HomePageView, MaterialHistoryListView, MaterialInActivesListView

app_name = 'materials'

urlpatterns = [
    path("dashboard/", HomePageView.as_view(), name="dashboard"),
    path("dashboard/inactives/", MaterialInActivesListView.as_view(),name="inactives"),
    path("dashboard/history/", MaterialHistoryListView.as_view(), name="history"),
    
]

sales/urls.py
from django.urls import path

from sales.views import CreateProductStockView, StockBarcodeView, StockView, remove_local_storage, sales, sales_history, stock_sell

app_name = "sales"

urlpatterns = [
    path("dashboard/", StockView.as_view(), name="dashboard"),
    path("dashboard/stock/sell/", stock_sell, name="stock-sell"),
    path("dashboard/stock/create/", CreateProductStockView.as_view(), name="stock-create"),
    path('dashboard/stock/remove/', remove_local_storage, name='stock-remove'),
    path('dashboard/sales/', sales, name='sales'),
    path('dashboard/sales/history', sales_history, name='sales-history'),
    path("dashboard/stock/barcodes/", StockBarcodeView.as_view(), name="stock-barcodes"),
    
    
    
]

spare/urls.py
from django.urls import path

from spare.views import SpareExportView, SpareHistoryListView, SpareListView, SpareTypeDeleteView, SpareTypeListView, SpareTypeUpdateView

app_name = 'spare'

# SPARE VIEWS
urlpatterns = [
    path("dashboard/spare/", SpareListView.as_view(), name="dashboard"),
    path("dashboard/spare/types/", SpareTypeListView.as_view(), name="spare_types"),
    path(
        "dashboard/spare/types/edit/<int:pk>/",
        SpareTypeUpdateView.as_view(),
        name="spare_types_update",
    ),
    path(
        "dashboard/spare/types/delete/<int:pk>/",
        SpareTypeDeleteView.as_view(),
        name="spare_types_delete",
    ),
    path(
        "dashboard/spare/history/",
        SpareHistoryListView.as_view(),
        name="spare_history",
    ),
    path(
        "dashboard/spare/export/",
        SpareExportView.as_view(),
        name="spare_export",
    ),
]

user/urls.py
from django.urls import path
from user.views import MainLoginView, MainLogoutView

app_name = "users"

urlpatterns = [
    path("login/", MainLoginView.as_view(), name="login"),
    path("login/", MainLogoutView.as_view(), name="logout")
]

materials/models.py
from django.db import models
from user.models import User
import random
from barcode import Code128
from barcode.writer import ImageWriter


def generate_unique_id():
    # Generate a random 10 digit ID
    return str(random.randint(1000000, 9999999))


AMOUNTS = (
    ("gram", "Gramm"),
    ("liter", "Litr"),
    ("kg", "Kilogramm"),
    ("point", "Dona"),
    ("meter", "Metr"),
)
CURRENCIES = (
    ("uzs", "UZS"),
    ("usd", "USD"),
)

ACTIVE = (("active", "Faol"), ("inactive", "Nofaol"), ("pending", "Kutilmoqda"))

ACTION_TYPES = (
    ("import", "Kirim"),
    ("export", "Chiqim"),
    ("update", "Yangilash"),
    ("delete", "O'chirish"),
    ("cancel", "Bekor qilish"),
    ("sold", "Sotish"),
    ("confirm", "Tasdiqlash"),
)

WHERE = (
    ("null", "--------"),
    ("material", "Homashyo ombori"),
    ("brak", "Brak mahsulot"),
    ("label", "Etiketika ombori"),
    ("production", "Ishlab chiqarish"),
    ("spare", "Ehtiyot qism ombori"),
    ("yaim", "Yarim tayyor mahsulot"),
    ("product", "Tayyor mahsulot ombori"),
    ("storage", "Mahsulot ombori"),
)


# MATERIAL TYPES, STORAGE AND HISTORY
class MaterialType(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class MaterialStorageHistory(models.Model):
    executor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    material = models.ForeignKey(MaterialType, on_delete=models.SET_NULL, null=True)

    action = models.CharField(choices=ACTION_TYPES, max_length=9)
    amount = models.CharField(default="0", max_length=255)
    amount_type = models.CharField(choices=AMOUNTS, max_length=5, default="meter")
    price = models.CharField(max_length=255, blank=True)
    price_type = models.CharField(choices=CURRENCIES, default="usd", max_length=5)
    where = models.CharField(choices=WHERE, max_length=16, default="null")

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)


class MaterialStorage(models.Model):
    material = models.ForeignKey(MaterialType, on_delete=models.PROTECT)

    amount = models.CharField(default="0", max_length=255)
    amount_type = models.CharField(choices=AMOUNTS, max_length=5)

    price = models.CharField(max_length=600, default=0, verbose_name="Narx")
    confirmed_price = models.CharField(
        max_length=600, default=0, verbose_name="Tasdiqlangan narx"
    )
    price_type = models.CharField(
        choices=CURRENCIES, default="usd", max_length=3, verbose_name="Pul birligi"
    )

    is_active = models.CharField(choices=ACTIVE, default="pending", max_length=8)

    import_comment = models.CharField(max_length=255, null=True, blank=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.material} - {self.amount} {self.get_amount_type_display()}"

    @classmethod
    def import_material(cls, request):
        material_type_id = request.POST.get("material")
        price = request.POST.get("price")
        confirmed_price = request.POST.get("confirmed_price")
        price_type = request.POST.get("price_type")
        amount_type = request.POST.get("amount_type")

        is_active = "active" if request.user.role == "ADMIN" else "pending"
        print(is_active)

        material_type = MaterialType.objects.get(id=material_type_id)

        material = MaterialStorage.objects.filter(
            material=material_type,
            price=price,
            confirmed_price=confirmed_price,
            price_type=price_type,
            amount_type=amount_type,
            is_active=is_active,
        )

        if material.exists():
            m = material.first()
            m.amount = float(m.amount) + float(request.POST.get("amount"))
            m.import_comment = request.POST.get("import_comment")
            m.save()

        else:
            MaterialStorage.objects.create(
                material=material_type,
                amount=float(request.POST.get("amount")),
                amount_type=amount_type,
                price=price,
                confirmed_price=confirmed_price,
                price_type=price_type,
                import_comment=request.POST.get("import_comment"),
                is_active=is_active,
            )

        MaterialStorageHistory.objects.create(
            executor=request.user,
            material=material_type,
            action="import",
            amount=float(request.POST.get("amount")),
            price=price,
            price_type=price_type,
            amount_type=amount_type,
            where="material",
        )

    @classmethod
    def accept_material(cls, request, material):
        MaterialStorageHistory.objects.create(
            executor=request.user,
            material=material.material,
            action="confirm",
            amount=material.amount,
            price=material.price,
            price_type=material.price_type,
            amount_type=material.amount_type,
            where="material",
        )

    @classmethod
    def cancel_material(cls, request, material):
        MaterialStorageHistory.objects.create(
            executor=request.user,
            material=material.material,
            action="cancel",
            amount=material.amount,
            price=material.price,
            price_type=material.price_type,
            amount_type=material.amount_type,
            where="material",
        )


# SPARE TYPES, STORAGE AND HISTORY
class SpareType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class SpareStorage(models.Model):
    spare = models.ForeignKey(
        SpareType, on_delete=models.PROTECT, verbose_name="Ehtiyot qism"
    )
    amount = models.CharField(max_length=255, verbose_name="Miqdori")
    amount_type = models.CharField(
        max_length=16, choices=AMOUNTS, default="meter", verbose_name="Miqdor turi"
    )

    price = models.CharField(max_length=600, default=0, verbose_name="Narxi")
    confirmed_price = models.CharField(
        max_length=600, default=0, verbose_name="Tasdiqlangan narxi"
    )

    price_type = models.CharField(
        choices=CURRENCIES, default="usd", max_length=3, verbose_name="Pul birligi"
    )

    is_active = models.CharField(
        choices=ACTIVE, default="active", max_length=8, verbose_name="Holati"
    )

    import_comment = models.CharField(max_length=255, verbose_name="Izoh")

    barcode = models.CharField(max_length=255, verbose_name="Barkod")

    updated_at = models.DateTimeField(auto_now=True, verbose_name="Oxirgi yangilanish")
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Qo'shilgan vaqti"
    )

    def __str__(self) -> str:
        return self.spare.name

    @classmethod
    def import_spare(cls, request):
        spare_id = request.POST.get("spare")
        price = request.POST.get("price")
        confirmed_price = request.POST.get("confirmed_price")
        price_type = request.POST.get("price_type")
        amount_type = request.POST.get("amount_type")
        barcode = request.POST.get("barcode")

        spare_type = SpareType.objects.get(id=spare_id)

        spare = cls.objects.filter(
            spare=spare_type,
            price=price,
            confirmed_price=confirmed_price,
            price_type=price_type,
            amount_type=amount_type,
            barcode=barcode,
            is_active="active",
        )

        if spare.exists():
            m = spare.first()
            m.amount = float(m.amount) + float(request.POST.get("amount"))
            m.import_comment = request.POST.get("import_comment")
            m.save()

        else:
            cls.objects.create(
                spare=spare_type,
                amount=float(request.POST.get("amount")),
                amount_type=amount_type,
                price=price,
                confirmed_price=confirmed_price,
                price_type=price_type,
                import_comment=request.POST.get("import_comment"),
                barcode=barcode,
                is_active="active",
            )

        SpareStorageHistory.objects.create(
            executor=request.user,
            spare=spare_type,
            action="import",
            amount=float(request.POST.get("amount")),
            price=price,
            price_type=price_type,
            amount_type=amount_type,
            where="spare",
        )

    def export(self, user, amount, where):
        SpareStorageHistory.objects.create(
            executor=user,
            spare=self.spare,
            action="export",
            amount=amount,
            amount_type=self.amount_type,
            price=self.price,
            price_type=self.price_type,
            where=where,
        )

        self.amount = float(self.amount) - float(amount)
        self.save()

        if float(self.amount) <= 0:
            self.delete()


class SpareStorageHistory(models.Model):
    executor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    spare = models.ForeignKey(SpareType, on_delete=models.SET_NULL, null=True)

    action = models.CharField(choices=ACTION_TYPES, max_length=9)
    amount = models.CharField(default="0", max_length=255)
    amount_type = models.CharField(choices=AMOUNTS, max_length=5, default="meter")
    price = models.CharField(max_length=255, blank=True)
    price_type = models.CharField(choices=CURRENCIES, default="usd", max_length=5)
    where = models.CharField(choices=WHERE, max_length=16, default="null")

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)


# LABEL TYPES, STORAGE AND HISTORY
class LabelType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class LabelStorage(models.Model):

materials/views.py
from django.shortcuts import render
from materials.models import MaterialStorage, MaterialStorageHistory
from materials.permissions import IsMaterialRole
from superuser.forms import InsertMaterialForm
from django.urls import reverse
from django.shortcuts import redirect
from django.views.generic import ListView

# Create your views here.

class HomePageView(IsMaterialRole, ListView):
    model = MaterialStorage
    paginate_by = 20
    template_name = "superadmin/home.html"

    def post(self, request, *args, **kwargs):
        MaterialStorage.import_material(request)
        return redirect(reverse("materials:dashboard"))

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["insert_material_form"] = InsertMaterialForm
        return context_data

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.order_by("-id").filter(is_active="active")
        return queryset
    
    
    
class MaterialInActivesListView(IsMaterialRole, ListView):
    model = MaterialStorage
    paginate_by = 20
    template_name = "superadmin/inactive_materials.html"

    def get_queryset(self):
        queryset = super().get_queryset().order_by("-id")
        queryset = queryset.filter(is_active="pending")
        return queryset
    
    
    
class MaterialHistoryListView(IsMaterialRole, ListView):
    model = MaterialStorageHistory
    template_name = "superadmin/materialhistory.html"
    paginate_by = 20
    ordering = ["-updated_at"]
    

templates/superadmin/materialhistory.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block sidebar_items %}
{% include './sidebar.html' %}
{% endblock sidebar_items %}


{% block content %}

<h3 class="mt-2">Operatsiyalar tarixi | Homashyolar</h3>
<hr>

<br>

<a href="{% url 'superuser:material_history_xls' %}" class="btn btn-success mb-3">Excelda olish </a>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th style="width: 30px;">#</th>
                <th>Homashyo nomi</th>
                <th>Bajaruvchi</th>
                <th>Operatsiya turi</th>
                <th>Miqdor</th>
                <th>Narx</th>
                <th>Qayerga</th>
                <th>Sana</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
            <tr>
                <td>{{forloop.counter0|add:page_obj.start_index}}</td>
                <td>{{obj.material}}</td>
                <td>{{obj.executor.role}}</td>
                <td>{{obj.get_action_display}}</td>
                <td>{{obj.amount|intcomma}} {{obj.get_amount_type_display}}</td>
                <td>{{obj.price|intcomma}} {{obj.get_price_type_display}}</td>
                <td>{{obj.get_where_display}}</td>
                <td>{{obj.created_at}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



{% if page_obj.has_next or page_obj.has_previous %}

<div class="pagination">
    <span class="step-links">

        <br>
        <h6 class="current">
            {{ page_obj.paginator.num_pages }} - {{ page_obj.number }} sahifa.
            </h4>
            <br>


            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page=1" {% endif %}>&laquo;Birinchi</a>
            |
            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }}"
                {%endif %}>‹ Oldingi</a> |




            <a class="pagination-btn" {% if page_obj.has_next %}
                href="?page={{ page_obj.next_page_number }} {% endif %}">Keyingi ›</a> |
            <a class="pagination-btn" {% if page_obj.has_next %} href="?page={{ page_obj.paginator.num_pages }}"
                {%endif%}>Oxirgi &raquo;</a>

    </span>
</div>

{% endif %}



{% endblock content %}

templates/superadmin/materialtype_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block sidebar_items %}
{% include './sidebar.html' %}
{% endblock sidebar_items %}


{% block content %}

<h3 class="mt-2">Homashyo turlari</h3>
<hr>
<br>

<form method="post">
    {% csrf_token %}
    {{object}}
    <br>

    <button type="submit" id="submit-btn" class="btn btn-danger mt-3">O'chirish</button>
</form>
<br>

<hr>





{% endblock content %}

templates/superadmin/sidebar.html
{% block sidebar_items %}
{% if request.user.role == "ADMIN" %}
<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">Homashyo ombori</a>
    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'superuser:dashboard' %}">Homashyo ombori</a>
        <a class="dropdown-item text-danger" href="{% url 'superuser:material_inactives' %}">Tasdiqlanmagan
            homashyolar</a>
        <a class="dropdown-item" href="{% url 'superuser:material_types' %}">Homashyo turlari</a>
        <a class="dropdown-item" href="{% url 'superuser:material_history' %}">Tarix</a>
    </div>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">Ehtiyot qismlar</a>
    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'superuser:spare_list' %}">Ehtiyot qism ombori</a>
        <a class="dropdown-item" href="{% url 'superuser:spare_export' %}">Ehtiyot qismlari eksport</a>
        <a class="dropdown-item" href="{% url 'superuser:spare_types' %}">Ehtiyot qism turlari</a>
        <a class="dropdown-item" href="{% url 'superuser:spare_history' %}">Tarix</a>
    </div>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">Etiketika</a>
    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'superuser:label_list' %}">Etiketika ombori</a>
        <a class="dropdown-item" href="{% url 'superuser:label_export' %}">Etiketika eksport</a>
        <a class="dropdown-item" href="{% url 'superuser:label_types' %}">Etiketika turlari</a>
        <a class="dropdown-item" href="{% url 'superuser:label_history' %}">Tarix</a>
    </div>
</div>



<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">Ishlab chiqarish</a>
    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'superuser:production_material_history' %}">Homashyo tarixi</a>
        <a class="dropdown-item" href="{% url 'superuser:send_yaim' %}">YaTMga mahsulot yuborish</a>
    </div>
</div>


<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'superuser:pre-production' %}" class="nav-link">Yarim tayyor  mahsulotlar</a>
</div>



<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">Tayyor mahsulot</a>
    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'superuser:stock' %}" class="nav-link">Tayyor  mahsulotlar</a>
        <a class="dropdown-item" href="{% url 'superuser:stock-sell' %}">Mijozga sotish</a>
        <a class="dropdown-item" href="{% url 'superuser:sales' %}">Savdo</a>
        <a class="dropdown-item" href="{% url 'superuser:sales-history' %}">Savdo tarixi</a>
    </div>
</div>



<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">Dizaynlar</a>
    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'superuser:design_home' %}" class="nav-link">Dizaynlar</a>
        <a class="dropdown-item" href="{% url 'superuser:design_price_history' %}" class="nav-link">Narxlar tarixi</a>
    </div>
</div>


<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'superuser:brak_list' %}" class="nav-link">Brak mahsulotlar</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'superuser:expenditure' %}" class="nav-link">Harajatlar</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'superuser:finance' %}" class="nav-link">Kirim & Chiqim</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'superuser:profiles' %}" class="nav-link">Menejerlar</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">Ishchilar</a>
    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'superuser:workers' %}">Ishchilar</a>
        <a class="dropdown-item" href="{% url 'superuser:unclosed-accounts' %}">Yopilmagan ish haqqilari</a>
        <a class="dropdown-item" href="{% url 'superuser:accounts-history' %}">Ish haqqi tarixi</a>
        <a class="dropdown-item" href="{% url 'superuser:register-workers-stats' %}">Ishlarni ro'yxatga olish</a>
    </div>
</div>


{% endif %}



{% if request.user.role == "MATERIAL" %}

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'materials:dashboard' %}" class="nav-link">Homashyo ombori</a>
</div>
<div class="sidebar-dropdown p-3 border-bottom dropdown">
<a href="{% url 'materials:inactives' %}" class="nav-link">Tasdiqlanmagan homashyolar</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'materials:history' %}" class="nav-link">Tarix</a>
</div>

    
{% endif %}
    


{% if request.user.role == "SALES" %}
<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'sales:dashboard' %}" class="nav-link">Tayyor mahsulotlar ombori</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'sales:stock-create' %}" class="nav-link">Mahsulot kiritish</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="dropdown-item" href="{% url 'sales:stock-sell' %}">Mijozga sotish</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="dropdown-item" href="{% url 'sales:sales' %}">Savdolar</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="dropdown-item" href="{% url 'superuser:sales-history' %}">Savdo tarixi</a>
</div>
{% endif %}


{% if request.user.role == "SPARE" %}
<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="dropdown-item" href="{% url 'spare:dashboard' %}">Ehtiyot qism ombori</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="dropdown-item" href="{% url 'spare:spare_export' %}">Ehtiyot qismlari eksport</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="dropdown-item" href="{% url 'spare:spare_types' %}">Ehtiyot qism turlari</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a class="dropdown-item" href="{% url 'spare:spare_history' %}">Tarix</a>
</div>

{% endif %}


{% if request.user.role == "DIRECTOR" %}

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'director:dashboard' %}" class="nav-link">Homashyo ombori</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'director:spare' %}" class="nav-link">Ehtiyot qism ombori</a>
</div>
    
<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'director:label' %}" class="nav-link">Etiketika ombori</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'director:pre-production' %}" class="nav-link">Yarim tayyor mahsulotlar</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'director:stock' %}" class="nav-link">Tayyor mahsulotlar ombori</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'director:sales' %}" class="nav-link">Savdolar</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'director:sales-history' %}" class="nav-link">Savdo tarixi</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'director:expenditure' %}" class="nav-link">Harajatlar</a>
</div>

<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'director:finance' %}" class="nav-link">Kirim/Chiqimlar</a>
</div>

    
{% endif %}
    



<div class="sidebar-dropdown p-3 border-bottom dropdown">
    <a href="{% url 'users:logout' %}" class="nav-link">Chiqish</a>
</div>
{% endblock sidebar_items %}
    