core/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static


def redirect_login(request):
    return redirect(reverse('users:login'))

urlpatterns = [
    
    path("admin/", admin.site.urls),
    path("auth/", include("user.urls", namespace="users")),
    path("superuser/", include("superuser.urls", namespace="superuser")),
    path("material/", include("materials.urls", namespace="materials")),
    path("sales/", include("sales.urls", namespace="sales")),
    path("spare/", include("spare.urls", namespace="spare")),
    path("director/", include("director.urls", namespace="director")),
    path("", redirect_login)
]


urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superuser/urls.py
from django.urls import path
from superuser.forms import SellBrak
from superuser.views import (
    BrakListView,
    DesignPriceHistoryView,
    DesignView,
    ExpenditureView,
    FinanceView,
    HomePageView,
    LabelExportView,
    LabelHistoryListView,
    LabelListView,
    LabelTypeDeleteView,
    LabelTypeListView,
    LabelTypeUpdateView,
    MaterialInActiveCancelView,
    MaterialInActiveUpdateView,
    MaterialTypeListView,
    MaterialTypeUpdateView,
    MaterialTypeDeleteView,
    MaterialHistoryListView,
    MaterialInActivesListView,
    ProductionMaterialHistory,
    SellBrakView,
    SpareListView,
    SpareTypeDeleteView,
    SpareTypeListView,
    SpareTypeUpdateView,
    SpareHistoryListView,
    SpareExportView,
    DesignDeleteView,
    StockBarcodeView,
    StockView,
    UserView,
    WorkerListCreateView,
    admin_account_details,
    admin_accounts_history,
    admin_design_details,
    admin_edit_design_materials,
    admin_insert_design_materials,
    admin_pre_production_send,
    admin_pre_production_send_list,
    admin_sales,
    admin_unclosed_salaries,
    admin_worker_account,
    admin_worker_credits,
    admin_worker_details,
    admin_worker_stats,
    admin_workers,
    production_send_yaim,
    remove_local_storage,
    sales_history,
    stock_sell,
)

from superuser.utils.generate_xls import *

app_name = "superuser"

urlpatterns = [
    path("dashboard/", HomePageView.as_view(), name="dashboard"),
    path(
        "dashboard/material-types/",
        MaterialTypeListView.as_view(),
        name="material_types",
    ),
    path(
        "dashboard/material-types/edit/<int:pk>/",
        MaterialTypeUpdateView.as_view(),
        name="material_types_update",
    ),
    path(
        "dashboard/material-types/delete/<int:pk>/",
        MaterialTypeDeleteView.as_view(),
        name="material_types_delete",
    ),
    path(
        "dashboard/history/",
        MaterialHistoryListView.as_view(),
        name="material_history",
    ),
    path(
        "dashboard/material/inactives/",
        MaterialInActivesListView.as_view(),
        name="material_inactives",
    ),
    path(
        "dashboard/material/inactives/confirm/<int:pk>/",
        MaterialInActiveUpdateView.as_view(),
        name="material_inactives_confirm",
    ),
    path(
        "dashboard/material/inactives/cancel/<int:pk>/",
        MaterialInActiveCancelView.as_view(),
        name="material_inactives_cancel",
    ),
]

# SPARE VIEWS
urlpatterns += [
    path("dashboard/spare/", SpareListView.as_view(), name="spare_list"),
    path("dashboard/spare/types/", SpareTypeListView.as_view(), name="spare_types"),
    path(
        "dashboard/spare/types/edit/<int:pk>/",
        SpareTypeUpdateView.as_view(),
        name="spare_types_update",
    ),
    path(
        "dashboard/spare/types/delete/<int:pk>/",
        SpareTypeDeleteView.as_view(),
        name="spare_types_delete",
    ),
    path(
        "dashboard/spare/history/",
        SpareHistoryListView.as_view(),
        name="spare_history",
    ),
    path(
        "dashboard/spare/export/",
        SpareExportView.as_view(),
        name="spare_export",
    ),
]

# LABEL VIEWS
urlpatterns += [
    path("dashboard/label/", LabelListView.as_view(), name="label_list"),
    path("dashboard/label/types/", LabelTypeListView.as_view(), name="label_types"),
    path(
        "dashboard/label/types/edit/<int:pk>/",
        LabelTypeUpdateView.as_view(),
        name="label_types_update",
    ),
    path(
        "dashboard/label/types/delete/<int:pk>/",
        LabelTypeDeleteView.as_view(),
        name="label_types_delete",
    ),
    path(
        "dashboard/label/history/",
        LabelHistoryListView.as_view(),
        name="label_history",
    ),
    path(
        "dashboard/label/export/",
        LabelExportView.as_view(),
        name="label_export",
    ),
]

# DESIGN VIEWS
urlpatterns += [
    path("dashboard/design/home/", DesignView.as_view(), name="design_home"),
    path(
        "dashboard/design/insert-materials/<int:pk>/",
        admin_insert_design_materials,
        name="design-insert-materials",
    ),
    path(
        "dashboard/design/edit-materials/<int:pk>/",
        admin_edit_design_materials,
        name="design-edit-materials",
    ),

    path(
        "dashboard/design/details/<int:pk>/",
        admin_design_details,
        name="design-details",
    ),
    path("dashboard/design/delete/<int:pk>/", DesignDeleteView.as_view(), name="design_delete"),
    path("dashboard/design/price/history/", DesignPriceHistoryView.as_view(), name="design_price_history"),

]

urlpatterns += [
    path("dashboard/production/material/history/", ProductionMaterialHistory.as_view(),
         name="production_material_history"),
    path("dashboard/production/brak/", BrakListView.as_view(), name="brak_list"),
    path("dashboard/production/brak/sell/<int:pk>/", SellBrakView.as_view(), name="sell_brak"),
    path("dashboard/production/send-yaim/", production_send_yaim, name="send_yaim"),
]

urlpatterns += [
    path("dashboard/expenditure/", ExpenditureView.as_view(), name="expenditure"),
]

urlpatterns += [
    path("dashboard/profiles/", UserView.as_view(), name="profiles"),
]

# FINANCE
urlpatterns += [
    path("dashboard/finance/", FinanceView.as_view(), name="finance"),
]

# PRE PRODUCTION
urlpatterns += [
    path("dashboard/pre-production/", admin_pre_production_send_list, name="pre-production"),
    path('dashboard/pre-production/send-list/<int:pk>', admin_pre_production_send,
         name='pre-production-send'),
]

# WORKERS

urlpatterns += [
    path("dashboard/workers/", admin_workers, name="workers"),
    path('dashboard/workers/<int:pk>/', admin_worker_details, name='worker-details'),
    path('dashboard/workers/account/<int:pk>/', admin_worker_account, name='worker-accounts'),
    path('dashboard/workers/account-details/<int:pk>/', admin_account_details, name='worker-account'),
    path('dashboard/workers/account/<int:wid>/stats/<int:aid>/', admin_worker_credits, name='worker-stats'),
    path('dashboard/workers/unclosed-accounts/', admin_unclosed_salaries, name='unclosed-accounts'),
    path('dashboard/workers/history/', admin_accounts_history, name='accounts-history'),
    path('dashboard/workers/stats/', admin_worker_stats, name='register-workers-stats'),
]

# STOCK

urlpatterns += [
    path("dashboard/stock/", StockView.as_view(), name="stock"),
    path("dashboard/stock/sell/", stock_sell, name="stock-sell"),
    path('dashboard/stock/remove/', remove_local_storage, name='stock-remove'),
    path('dashboard/sales/', admin_sales, name='sales'),
    path('dashboard/sales/history', sales_history, name='sales-history'),

    path("dashboard/stock/barcodes/", StockBarcodeView.as_view(), name="stock-barcodes"),
]

# EXCEL GENERATORS
urlpatterns += [
    path(
        "dashboard/material/history/generate-xls/",
        GenerateMaterialHistoryExcel.as_view(),
        name="material_history_xls",
    ),
    path(
        "dashboard/material/generate-xls/",
        GenerateMaterialExcel.as_view(),
        name="material_xls",
    ),
    path(
        "dashboard/spare/history/generate-xls/",
        GenerateSpareHistoryExcel.as_view(),
        name="spare_history_xls",
    ),
    path(
        "dashboard/spare/generate-xls/",
        GenerateSpareExcel.as_view(),
        name="spare_xls",
    ),
    path(
        "dashboard/label/history/generate-xls/",
        GenerateLabelHistoryExcel.as_view(),
        name="label_history_xls",
    ),
    path(
        "dashboard/label/generate-xls/",
        GenerateLabelExcel.as_view(),
        name="label_xls",
    ),

    path(
        "dashboard/design/generate-xls/",
        GenerateDesignExcel.as_view(),
        name="design_xls",
    ),

    path(
        "dashboard/expenditure/generate-xls/",
        GenerateExpenditureExcel.as_view(),
        name="expenditure_xls",
    ),

    path(
        "dashboard/finance/generate-xls/",
        GenerateFinanceExcel.as_view(),
        name="finance_xls",
    ),
    path(
        "dashboard/design/history/generate-xls/",
        GenerateDesignPriceHistoryExcel.as_view(),
        name="design_price_history_xls",
    ),
]

# TODO
# * Nazoratchi / Sotuvchi / Zapchast / Seryo ----> Profillar


# Pul kirimlari
# Brak mahsulot
# Savdo

templates/superadmin/design/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block sidebar_items %}
{% include '../sidebar.html' %}
{% endblock sidebar_items %}


{% block content %}

<h3 class="mt-2">Dizayn</h3>
<hr>
<br>

<form method="post">
    {% csrf_token %}
    {{object}}
    <br>
    <div class="mt-3">

    <a href="{% url 'superuser:design_home' %}" class="btn btn-secondary">Ortga</a>
    <button type="submit" id="submit-btn" class="btn btn-danger">O'chirish</button>
    </div>
</form>
<br>

<hr>





{% endblock content %}

templates/superadmin/design/details.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load mathfilters %}
{% load calcs_tags %}
{% load humanize %}

{% block sidebar_items %}
{% include '../sidebar.html' %}
{% endblock sidebar_items %}


{% block choice %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
{% endblock choice %}


{% block content %}
<div class="card p-4 mt-3">
    <div class="card-title h3">{{design.name}}</div>
    <table class="table mb-4" id="materialTable">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Tur</th>
                <th>Miqdor</th>
                <th>Umumiy narx</th>
                <th>Pul birligi</th>
            </tr>
        </thead>

        <tbody>
            {% for material in design.designfield_set.all %}
            <tr>
                <td>{{material}}</td>
                <td>Serio</td>
                <td>{{material.amount|dec_div:design.amount}} <b>gr</b></td>
                <td>
                    {% if material.material_type.materialstorage_set.all.count > 0%}
                        {{ material.material_type.materialstorage_set.last.price|clear_mul_serio:material.amount}}
                    {% else %}
                        0
                    {% endif %}
                </td>
                <td>
                    {% if material.material_type.materialstorage_set.all.count > 0%}
                    {{ material.material_type.materialstorage_set.last.get_price_type_display}}
                    {% else %}
                    0
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            {% for label in design.designlabel_set.all %}
            <tr>
                <td>{{label.label}}</td>
                <td>Etiketika</td>
                <td>1</td>
                <td>
                    {% if label.price %}
                        {{label.price}}
                    {% else %}
                        {{label.label.labelstorage_set.first.price}}
                    {% endif %}
                </td>
                <td>
                    {% if label.price %}
                        UZS
                    {% else %}
                        {{label.label.labelstorage_set.first.get_price_type_display}}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            {% for immut in design.designimmutable_set.all %}
            <tr>
                <td>{{immut.name}}</td>
                <td>O'zgarmas</td>
                <td>1</td>
                <td>{{immut.cost}}</td>
                <td>{% if immut.calc_type == 'sum' %} UZS {% else %} % {% endif %}</td>
            </tr>
            {% endfor %}
           

        </tbody>

    </table>
    <div class="mb-1">
        <b>Umumiy og'irlik : <span id="weight">
            {{design.weight}} gr
        </span></b>
    </div>
    <div class="d-flex mb-3">
        <b>Umumiy</b>
        <div class="mx-3">
            <b class="font-weight-bold" id="usd_total">
                {{design.total}} so'm
            </b>
        </div>
        
    </div>
    <div>
    <a href="{% url 'superuser:design_home' %}" class="btn btn-primary">Ortga</a>

    </div>

</div>


<script>
    var table = document.getElementById("materialTable");
    var totalUZS = 0;
    var totalUSD = 0;
    var totalWeight = 0;
    for (var i = 1; i < table.rows.length; i++) {
        let txt = table.rows[i].cells[3].innerText
        if (table.rows[i].cells[1].innerText === 'Serio') {
            totalWeight += parseFloat(table.rows[i].cells[2].innerText.replace(/,/g, '.'));
        }
        if (table.rows[i].cells[4].innerText === 'UZS') {
            totalUZS += parseFloat(table.rows[i].cells[3].innerText)
            table.rows[i].cells[3].innerText.replace(/,/g, '.');
        }
        if (table.rows[i].cells[4].innerText === 'USD') {
            totalUSD += parseFloat(table.rows[i].cells[3].innerText.replace(/,/g, '.'));
        }


    }

    totalUSD = totalUSD / parseFloat('{{design.amount}}')

    let percent = 0;
    for (var i = 1; i < table.rows.length; i++) {

        if (table.rows[i].cells[4].innerText === '%') {
            percent += parseFloat(table.rows[i].cells[3].innerText);
        }
    }
    let convert = parseFloat('{{exchange}}');
    let total_end = parseFloat(convert) * parseFloat(totalUSD) + parseFloat(totalUZS)
    let with_percent = total_end / 100 * (100 + percent)

    document.getElementById('usd_to_uzs').innerHTML = parseFloat(convert) + ' so`m';
    document.getElementById('percent_total').innerHTML = percent.toLocaleString() + '%';
    document.getElementById('end_total').innerHTML = parseFloat(with_percent).toFixed(3) + ' so`m';


</script>



{% endblock content %}

templates/superadmin/design/history.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block sidebar_items %}
{% include '../sidebar.html' %}
{% endblock sidebar_items %}


{% block content %}


<h3>Filterlash</h3>
<hr>

<form action="">
    <div class="row gy-2">
        <div class="col-sm-4">
            <div class="form-group">
                <label for="">Dizayn nomi</label>
                <input type="text" class="form-control" name="name">
            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group">
                <label for="">Sana (...dan)</label>
                <input type="date" class="form-control" name="date_from">
            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group">
                <label for="">Sana (...gacha)</label>
                <input type="date" class="form-control" name="date_to">
            </div>
        </div>

    </div>
<div class="mt-3">

    <button class="btn btn-primary">
    Qidirish
    </button>
    <a href="{% url 'superuser:design_price_history_xls' %}?name={{name}}&date_from={{date_from}}&date_to={{date_to}}" class="btn btn-success">Excelda olish </a>

</div>
</form>

<div class="table-responsive mt-3">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Dizayn nomi</th>
                <th>Og'irligi</th>
                <th>Kurs</th>
                <th>Homashyo narxi</th>
                <th>Harajatlar</th>
                <th>Brak</th>
                <th>Bino amortizatsiya</th>
                <th>Stanok amortizatsiya</th>
                <th>Boshqa</th>
                <th>Sana</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
            <tr>
                <td>{{forloop.counter0|add:page_obj.start_index}}</td>
                <td>{{obj.design_name}}</td>
                <td>{{obj.weight|truncatechars:7}} gr</td>
                <td>{{obj.exchange|truncatechars:7}} so'm</td>
                <td>{{obj.materials|truncatechars:7}} $</td>
                <td>{{obj.expense|truncatechars:7}} so'm</td>
                <td>{{obj.invalid|truncatechars:7}} so'm</td>
                <td>{{obj.building|truncatechars:7}} so'm</td>
                <td>{{obj.machine|truncatechars:7}} so'm</td>
                <td>{{obj.another_percent|truncatechars:7}} so'm</td>
                <th>{{obj.created_at}}</th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



{% if page_obj.has_next or page_obj.has_previous %}

<div class="pagination">
    <span class="step-links">

        <br>
        <h6 class="current">
            {{ page_obj.paginator.num_pages }} - {{ page_obj.number }} sahifa.
            </h4>
            <br>


            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page=1" {% endif %}>&laquo;Birinchi</a>
            |
            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }}"
                {%endif %}>‹ Oldingi</a> |




            <a class="pagination-btn" {% if page_obj.has_next %}
                href="?page={{ page_obj.next_page_number }} {% endif %}">Keyingi ›</a> |
            <a class="pagination-btn" {% if page_obj.has_next %} href="?page={{ page_obj.paginator.num_pages }}"
                {%endif%}>Oxirgi &raquo;</a>

    </span>
</div>

{% endif %}



{% endblock content %}

templates/superadmin/design/list_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block sidebar_items %}
{% include '../sidebar.html' %}
{% endblock sidebar_items %}


{% block content %}

<h3 class="mt-2">Dizayn kiritish</h3>
<hr>

<form method="post">
    <div class="column-2">
        {% csrf_token %}
        {{form|crispy}}
    </div>
    <button type="submit" id="submit-btn" class="btn btn-primary">Kiritish</button>
</form>

<br><br>
<h3>Filterlash</h3>
<hr>

<form action="">
    <div class="row gy-2">
        <div class="col-sm-4">
            <div class="form-group">
                <label for="">Nom</label>
                <input type="text" class="form-control" placeholder="Nom bo'yicha qidirish" name="name">
            </div>
        </div>
        
        <div class="col-sm-4">
            <div class="form-group">
                <label for="">Jinsi</label>
                <select name="sex" class="form-control">
                    <option value="">Jinsi tanlang</option>
                    <option value="male">Erkak</option>
                    <option value="female">Ayol</option>
                    <option value="young">O'smir</option>
                    <option value="baby">Bola</option>
                </select>
            </div>
        </div>
        
        <div class="col-sm-4">
            <div class="form-group">
                <label for="">Mavsum</label>
                <select name="season" class="form-control">
                    <option value="">Mavsumni tanlang</option>
                    <option value="winter">Qish</option>
                    <option value="summer">Yoz</option>
                </select>
            </div>
        </div>
        
   
        
        

    </div>
<div class="mt-3">

    <button class="btn btn-primary">
    Qidirish
    </button>
    <a href="{% url 'superuser:design_xls' %}?name={{name}}&sex={{sex}}&season={{season}}" class="btn btn-success">Excelda olish </a>

</div>
</form>

<div class="table-responsive mt-3">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Dizayn nomi</th>
                <th>Jins</th>
                <th>Mavsum</th>
                <th>Og'irlik</th>
                <th>Xomashyo narxi</th>
                <th>Harajatlar</th>
                <th>Brak</th>
                <th>Bino</th>
                <th>Stanok</th>
                <th>Boshqa</th>
                
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
            <tr>
                <td>{{forloop.counter0|add:page_obj.start_index}}</td>
                <td>{{obj.name}}</td>
                <td>{{obj.get_sex_display}}</td>
                <td>{{obj.get_season_display}}</td>
                <td>{{obj.weight|truncatechars:7}} gr</td>
                <td>{{obj.materials|truncatechars:7}} $</td>
                <td>{{obj.expense|truncatechars:7}} so'm</td>
                <td>{{obj.invalid|truncatechars:7}} so'm</td>
                <td>{{obj.building|truncatechars:7}} so'm</td>
                <td>{{obj.machine|truncatechars:7}} so'm</td>
                <td>{{obj.another_percent|truncatechars:7}} so'm</td>
                <td>
                    <div class="d-flex gap-2 flex-row-reverse">
                        <a href="{% url 'superuser:design_delete' obj.id %}" class="btn btn-danger">
                            <i class="fa fa-trash"></i>
                        </a>
                        {% if page %}
                        <a href="{% url 'superuser:design-edit-materials' obj.id %}?page={{page}}" class="btn btn-success">
                            <i class="fa fa-pencil"></i>
                        </a>
                        {% else %}
                        <a href="{% url 'superuser:design-edit-materials' obj.id %}" class="btn btn-success">
                            <i class="fa fa-pencil"></i>
                        </a>
                        {% endif %}
                        <a href="{% url 'superuser:design-details' obj.id %}" class="btn btn-primary">
                            <i class="fa fa-eye"></i>
                        </a>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



{% if page_obj.has_next or page_obj.has_previous %}

<div class="pagination">
    <span class="step-links">

        <br>
        <h6 class="current">
            {{ page_obj.paginator.num_pages }} - {{ page_obj.number }} sahifa.
            </h4>
            <br>


            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page=1" {% endif %}>&laquo;Birinchi</a>
            |
            <a class="pagination-btn" {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }}"
                {%endif %}>‹ Oldingi</a> |




            <a class="pagination-btn" {% if page_obj.has_next %}
                href="?page={{ page_obj.next_page_number }} {% endif %}">Keyingi ›</a> |
            <a class="pagination-btn" {% if page_obj.has_next %} href="?page={{ page_obj.paginator.num_pages }}"
                {%endif%}>Oxirgi &raquo;</a>

    </span>
</div>

{% endif %}



{% endblock content %}